services:
  - type: web
    name: hardware-store-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_PORT
        value: 8080
      - key: DB_HOSTNAME
        fromDatabase:
          name: hardware-store-db
          property: hostname
      - key: DB_PORT
        fromDatabase:
          name: hardware-store-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: hardware-store-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: hardware-store-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: hardware-store-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: LOGGING_HIBERNATE_SQL
        value: INFO
      - key: LOGGING_HIBERNATE_BINDER
        value: INFO
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRATION
        sync: false
      - key: JWT_REFRESH_EXPIRATION
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: OTP_EXPIRY_MINUTES
        sync: false

databases:
  - name: hardware-store-db
    plan: free
