spring:
  application:
    name: hardware_store
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  h2:
    console:
      enabled: false

logging:
  level:
    org.springframework.boot: INFO
    org.hibernate.SQL: ${LOGGING_HIBERNATE_SQL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_HIBERNATE_BINDER}

server:
  port: ${APP_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
